export const tcListEx = [
  {
    tcSeq: 1,
    serviceName: "로그인",
    testcaseName: "아이디 입력 필드 디폴트 문구 확인",
    priority: "HIGH",
    precondition: "구매 내역이 있는 계정 로그인 상태",
    testStep: "1. 로그인 버튼 선택\n2. 로그인 팝업 표시 항목 확인",
    expectedResult:
      "1. 표시 항목 확인\n- '로그인' 문구\n- [X] 버튼\n- '아이디/패스워드로 로그인해주세요' 안내 문구\n- 아이디 입력 필드\n- 패스워드 입력 필드\n- [취소], [확인] 버튼",
    checked: false,
  },
  {
    tcSeq: 2,
    serviceName: "로그인",
    testcaseName: "아이디 입력 필드 디폴트 문구 확인",
    priority: "MEDIUM",
    precondition: "리뷰 작성 화면 진입 상태",
    testStep: "1. 로그인 버튼 선택\n2. 로그인 팝업 표시 항목 확인",
    expectedResult:
      "1. 표시 항목 확인\n- '로그인' 문구\n- [X] 버튼\n- '아이디/패스워드로 로그인해주세요' 안내 문구\n- 아이디 입력 필드\n- 패스워드 입력 필드\n- [취소], [확인] 버튼",
    checked: false,
  },
  {
    tcSeq: 3,
    serviceName: "로그인",
    testcaseName: "아이디 입력 필드 디폴트 문구 확인",
    priority: "MEDIUM",
    precondition: "리뷰 작성 화면 진입 상태",
    testStep: "1. 로그인 버튼 선택\n2. 로그인 팝업 표시 항목 확인",
    expectedResult:
      "1. 표시 항목 확인\n- '로그인' 문구\n- [X] 버튼\n- '아이디/패스워드로 로그인해주세요' 안내 문구\n- 아이디 입력 필드\n- 패스워드 입력 필드\n- [취소], [확인] 버튼",
    checked: false,
  },
  {
    tcSeq: 4,
    serviceName: "로그인",
    testcaseName: "아이디 입력 필드 디폴트 문구 확인",
    priority: "MEDIUM",
    precondition: "리뷰 작성 화면 진입 상태",
    testStep: "1. 로그인 버튼 선택\n2. 로그인 팝업 표시 항목 확인",
    expectedResult:
      "1. 표시 항목 확인\n- '로그인' 문구\n- [X] 버튼\n- '아이디/패스워드로 로그인해주세요' 안내 문구\n- 아이디 입력 필드\n- 패스워드 입력 필드\n- [취소], [확인] 버튼",
    checked: false,
  },
  {
    tcSeq: 5,
    serviceName: "로그인",
    testcaseName: "아이디 입력 필드 디폴트 문구 확인",
    priority: "MEDIUM",
    precondition: "리뷰 작성 화면 진입 상태",
    testStep: "1. 로그인 버튼 선택\n2. 로그인 팝업 표시 항목 확인",
    expectedResult:
      "1. 표시 항목 확인\n- '로그인' 문구\n- [X] 버튼\n- '아이디/패스워드로 로그인해주세요' 안내 문구\n- 아이디 입력 필드\n- 패스워드 입력 필드\n- [취소], [확인] 버튼",
    checked: false,
  },
  {
    tcSeq: 6,
    tcId: "AD-로그인-004",
    serviceName: "로그인",
    testcaseName: "비밀번호 입력 필드 마스킹 확인",
    priority: "LOW",
    precondition: "로그인 팝업 진입 상태",
    testStep: "1. 비밀번호 입력\n2. 입력값 표시 형태 확인",
    expectedResult: "1. 입력값이 마스킹(*) 처리되어 표시된다.",
    checked: false,
  },
  {
    tcSeq: 7,
    tcId: "AD-로그인-005",
    serviceName: "로그인",
    testcaseName: "로그인 실패 시 에러 메시지 표시 확인",
    priority: "HIGH",
    precondition: "잘못된 비밀번호 입력 상태",
    testStep: "1. 잘못된 비밀번호 입력\n2. 로그인 버튼 클릭",
    expectedResult: "1. “아이디 또는 비밀번호를 확인해주세요.” 문구 노출",
    checked: false,
  },
  {
    tcSeq: 8,
    tcId: "AD-로그인-006",
    serviceName: "로그인",
    testcaseName: "자동 로그인 체크박스 동작 확인",
    priority: "MEDIUM",
    precondition: "로그인 팝업 진입 상태",
    testStep: "1. 자동 로그인 체크박스 클릭\n2. 로그인 유지 여부 확인",
    expectedResult: "1. 체크 시 세션이 만료될 때까지 로그인 상태 유지됨",
    checked: false,
  },
  {
    tcSeq: 9,
    tcId: "AD-로그인-007",
    serviceName: "로그인",
    testcaseName: "아이디 저장 기능 확인",
    priority: "LOW",
    precondition: "아이디 저장 옵션 활성화",
    testStep: "1. 로그인 시 아이디 저장 선택\n2. 재진입 시 아이디 표시 여부 확인",
    expectedResult: "1. 재진입 시 아이디 필드에 이전 입력값 자동 표시",
    checked: false,
  },
  {
    tcSeq: 10,
    tcId: "AD-로그인-008",
    serviceName: "로그인",
    testcaseName: "로그인 성공 후 메인 페이지 이동 확인",
    priority: "HIGH",
    precondition: "정상 로그인 계정 보유",
    testStep: "1. 정상 계정으로 로그인\n2. 로그인 성공 후 화면 이동 확인",
    expectedResult: "1. 메인 페이지로 정상 이동됨",
    checked: false,
  },
  {
    tcSeq: 11,
    tcId: "AD-로그인-009",
    serviceName: "로그인",
    testcaseName: "비밀번호 찾기 링크 이동 확인",
    priority: "LOW",
    precondition: "로그인 팝업 진입 상태",
    testStep: "1. '비밀번호 찾기' 클릭\n2. 페이지 이동 확인",
    expectedResult: "1. 비밀번호 재설정 페이지로 이동됨",
    checked: false,
  },
  {
    tcSeq: 12,
    tcId: "AD-로그인-010",
    serviceName: "로그인",
    testcaseName: "회원가입 링크 이동 확인",
    priority: "LOW",
    precondition: "로그인 팝업 진입 상태",
    testStep: "1. '회원가입' 클릭\n2. 페이지 이동 확인",
    expectedResult: "1. 회원가입 페이지로 이동됨",
    checked: false,
  },
  {
    tcSeq: 13,
    tcId: "AD-로그인-011",
    serviceName: "로그인",
    testcaseName: "자동 로그인 해제 동작 확인",
    priority: "MEDIUM",
    precondition: "자동 로그인 설정 계정 상태",
    testStep: "1. 자동 로그인 해제 클릭\n2. 세션 유지 여부 확인",
    expectedResult: "1. 로그아웃 시 자동 로그인이 해제됨",
    checked: false,
  },
  {
    tcSeq: 14,
    tcId: "AD-로그인-012",
    serviceName: "로그인",
    testcaseName: "비밀번호 입력 시 특수문자 처리 확인",
    priority: "LOW",
    precondition: "로그인 팝업 진입 상태",
    testStep: "1. 특수문자 포함 비밀번호 입력\n2. 로그인 시도",
    expectedResult: "1. 특수문자 포함 시에도 정상 로그인됨",
    checked: false,
  },
  {
    tcSeq: 15,
    tcId: "AD-로그인-013",
    serviceName: "로그인",
    testcaseName: "세션 타임아웃 시 로그인 유지 여부 확인",
    priority: "MEDIUM",
    precondition: "로그인 후 일정 시간 경과 상태",
    testStep: "1. 세션 타임아웃 발생 유도\n2. 상태 확인",
    expectedResult: "1. 세션 만료 후 재로그인 요구됨",
    checked: false,
  },
  {
    tcSeq: 16,
    tcId: "AD-로그인-014",
    serviceName: "로그인",
    testcaseName: "다중 로그인 제한 확인",
    priority: "HIGH",
    precondition: "동일 계정으로 다른 기기 로그인 상태",
    testStep: "1. 새로운 기기에서 로그인\n2. 기존 세션 유지 여부 확인",
    expectedResult: "1. 이전 세션 자동 로그아웃됨",
    checked: false,
  },
  {
    tcSeq: 17,
    tcId: "AD-로그인-015",
    serviceName: "로그인",
    testcaseName: "OAuth(Google) 로그인 동작 확인",
    priority: "HIGH",
    precondition: "Google 계정 연동 설정 완료 상태",
    testStep: "1. Google 로그인 버튼 클릭\n2. 인증 완료 후 리디렉션 확인",
    expectedResult: "1. 정상적으로 로그인 완료되고 메인 페이지로 이동됨",
    checked: false,
  },
  {
    tcSeq: 18,
    tcId: "AD-로그인-016",
    serviceName: "로그인",
    testcaseName: "OAuth(Kakao) 로그인 동작 확인",
    priority: "HIGH",
    precondition: "Kakao 계정 연동 설정 완료 상태",
    testStep: "1. Kakao 로그인 버튼 클릭\n2. 인증 완료 후 리디렉션 확인",
    expectedResult: "1. 정상적으로 로그인 완료되고 메인 페이지로 이동됨",
    checked: false,
  },
  {
    tcSeq: 19,
    tcId: "AD-로그인-017",
    serviceName: "로그인",
    testcaseName: "로그아웃 기능 동작 확인",
    priority: "MEDIUM",
    precondition: "로그인 상태",
    testStep: "1. 로그아웃 버튼 클릭\n2. 세션 종료 확인",
    expectedResult: "1. 로그인 화면으로 전환됨\n2. 세션 정보 초기화됨",
    checked: false,
  },
  {
    tcSeq: 20,
    tcId: "AD-로그인-018",
    serviceName: "로그인",
    testcaseName: "로그인 실패 후 재시도 시 정상 동작 확인",
    priority: "MEDIUM",
    precondition: "이전 실패 이력 존재",
    testStep: "1. 잘못된 비밀번호로 로그인 시도\n2. 이후 올바른 비밀번호로 재시도",
    expectedResult: "1. 재시도 시 정상 로그인 가능",
    checked: false,
  },
];
